package main

import (
	"crypto/ed25519"
	"crypto/rand"
	"crypto/sha3"
	"encoding/base32"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func onionFixture(t *testing.T) (string, string) {
	t.Helper()
	root := t.TempDir()
	pub, _, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	checksum := sha3.Sum256(append(append([]byte(".onion checksum"), pub...), 3))
	onion := strings.ToLower(base32.StdEncoding.EncodeToString(append(append(append([]byte{}, pub...), checksum[:2]...), 3))) + ".onion"
	// These parser fixtures are not usable service identities. Real keys are
	// generated by the pinned Tor image with networking disabled.
	for name, b := range map[string][]byte{
		"hostname":              []byte(onion + "\n"),
		"hs_ed25519_public_key": append([]byte("== ed25519v1-public: type0 ==\x00\x00\x00"), pub...),
		"hs_ed25519_secret_key": append([]byte("== ed25519v1-secret: type0 ==\x00\x00\x00"), make([]byte, 64)...),
	} {
		if err := os.WriteFile(filepath.Join(root, name), b, 0600); err != nil {
			t.Fatal(err)
		}
	}
	return root, onion
}

func TestOnionContinuityRejectsReplacementSecretAndMissingRecord(t *testing.T) {
	root, onion := onionFixture(t)
	id, err := readOnionIdentity(root)
	if err != nil || id.Onion != onion {
		t.Fatalf("parse: %v", err)
	}
	record := filepath.Join(t.TempDir(), "identity.json")
	if retainOnionIdentity(record, id, false) == nil {
		t.Fatal("accepted missing continuity evidence")
	}
	if err = retainOnionIdentity(record, id, true); err != nil {
		t.Fatal(err)
	}
	if err = retainOnionIdentity(record, id, false); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(root, "hs_ed25519_secret_key")
	b, _ := os.ReadFile(path)
	b[45] ^= 1
	if err = os.WriteFile(path, b, 0600); err != nil {
		t.Fatal(err)
	}
	changed, err := readOnionIdentity(root)
	if err != nil {
		t.Fatal(err)
	}
	if retainOnionIdentity(record, changed, true) == nil {
		t.Fatal("accepted changed secret with unchanged hostname")
	}
}

func TestOnionIdentityRejectsMalformedAndLinkedFiles(t *testing.T) {
	for _, name := range []string{"hostname", "hs_ed25519_public_key", "hs_ed25519_secret_key"} {
		t.Run(name, func(t *testing.T) {
			root, _ := onionFixture(t)
			path := filepath.Join(root, name)
			b, _ := os.ReadFile(path)
			b[0] ^= 1
			if err := os.WriteFile(path, b, 0600); err != nil {
				t.Fatal(err)
			}
			if _, err := readOnionIdentity(root); err == nil {
				t.Fatal("accepted malformed identity")
			}
			if err := os.Rename(path, path+"-original"); err != nil {
				t.Fatal(err)
			}
			if err := os.Symlink(path+"-original", path); err != nil {
				t.Fatal(err)
			}
			if _, err := readOnionIdentity(root); err == nil {
				t.Fatal("accepted identity link")
			}
		})
	}
}
